auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “M's Blog”
title: M blog
description: Everything about M.
url: https://melony315.github.io/
feed: /atom.xml
author_info: <a href="https://melony315.github.io/">Melony315</a>
