# ----------- CONFIGURABLE START -----------
title:            "M blog"
description:      "侃侃理想、谈谈人生、敲敲代码。"
url:              https://melony315.github.io/M/ # 域名
signoff:          "M" # Your name
#facebook_appid:   #liberxue
#google_analytics: 
share:            true 
# 分页
paginate: 10
paginate_path:"page:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false

  - name:          软件
    url:          /book
    external:     false

  - name:         归档
    url:          /archives
    external:     false

# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
